# Generated by Django 4.2.5 on 2023-09-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default='img/None/no-img.jpg', upload_to='uploads/product/'),
        ),
    ]
