# Generated by Django 4.2.5 on 2023-09-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'slug')},
        ),
    ]
