# Generated by Django 4.2.5 on 2023-09-30 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
