# Generated by Django 4.2.5 on 2023-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
    ]
